import React, {Component} from 'react'
import { 
   Platform,
   StyleSheet,
   NativeModules,
} from 'react-native'


const {StatusBarManager} = NativeModules
export const S = StyleSheet.create({
    frdhead:{
        position:'relative',
        height:128,
        width:'100%',
        paddingTop:StatusBarManager.HEIGHT,
        backgroundColor: '#d53c32',
        justifyContent:'space-around',
    },
    frdheadqq:{
        paddingHorizontal:'1%',
        flexDirection:'row',
        alignItems:'center',
    },
    frdheadqqtext:{
        color:'#fff',
        fontSize:10,
        fontWeight:'bold',
    },
    frdheadadduser:{
        width:'100%',
        flexDirection:'row',
        paddingHorizontal:'3%',
        justifyContent:'space-between',
        alignItems:'center',
        // marginLeft: 5,
    },
    frdheaddt:{
        width:142,
        height:30,
        // padding:-2,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        borderWidth: 1,
        borderColor:'#eee',
        borderRadius:25,
        overflow:'hidden',
    },
    frdheaddttext:{
        width:70,
        height:28,
        fontSize:14,
        lineHeight:28,
        textAlign:'center',
        borderRadius:16,
    },
    frdusercz:{
        flexDirection:'row',
        justifyContent:'space-around',
        alignItems:'center',
    },
    usercz:{
        flexDirection:'row',
        alignItems:'center',
    },
    usercztex:{
        fontSize:15,
        color:'#fff',
    },
    followfrd:{
        width:'100%',
        // height:125,
        paddingHorizontal:'2%',
        justifyContent:'space-around',
        paddingTop:10,
        borderBottomWidth:1,
        borderColor:'#eee',
    },
    followfrdtb:{
        flexDirection:'row',
        alignItems:'center',
    },
    followfrdtext:{
        fontSize:13,
        color:'#000',
        marginRight:5,
    },
    followfrdzh:{
        width:'100%',
        height:70,
        flexDirection:'row',
    },
    followfrdlist:{
        height:70,
        marginRight: 20,
        alignItems:'center',
    },
    followfrdlisttp:{
        width:50,
        height:50,
        borderRadius:25,
    },
    frienddynamic:{
        // height:345,
        flex:1,
        justifyContent:'space-around',
        // paddingHorizontal:'3%'
    },
    frddynamichx:{
        height:345,
        justifyContent:'space-around',
    },
    dynamicauthor:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingHorizontal:'3%'
    },
    dynamicauthortp:{
        width:41,
        height:41,
        borderRadius:20,
    },
    authordes:{
        width:'81%',
        flexDirection:'row',
        justifyContent:'space-between',
    },
    authorfabu:{
        flexDirection:'row',
        // justifyContent:'space-between',
    },
    guanzhu:{
        width:62,
        height:26,
        backgroundColor:'#f54f3f',
        borderRadius:13,
        color:'#fff',
        fontSize:12,
        textAlign:'center',
        lineHeight:26,
    },
    dynamicdes:{
        width:'100%',
        paddingHorizontal:'3%',
        justifyContent:'space-around',
        alignItems:'flex-end',
    },
    ImageBackground:{
        width:324,
        height:194,
        padding:6,
        borderRadius:6,
        overflow:'hidden',
        justifyContent:'space-between',
        marginBottom:15,
    },
    ecy:{
        width:66,
        height:21,
        borderColor:'#fff',
        borderWidth:1,
        backgroundColor:'#000',
        fontSize:10,
        textAlign:'center',
        lineHeight:21,
        borderRadius:10,
        color:'#fff',
        opacity:0.4,
    },
    backtext:{
        flexDirection:'row',
        justifyContent:'space-between',
    },
    Followusercz:{
        width:324,
        height:36,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        // backgroundColor:'pink'
    },
    dznum:{
        alignItems:'flex-start',
        fontSize:11,
        marginLeft:5,
        color:'#d73146',
     },
})